project:
  type: book
  output-dir: docs

book:
  title: Neurowissenschaft im Computerlab
  subtitle: Kurs FS 2025, Bachelor Neurowissenschaften, Universität Bern
  author: Gerda Wyssen, Enea Weber, Daniel Fitze, and Andrew Ellis
  date: "Feb 15 2025"
  edition: 1
  reader-mode: false
  cover-image: imgs/logo.png
  favicon: imgs/logo.png
  site-url: https://kogpsy.github.io/neuroscicomplabFS25/
  page-navigation: true
  search: true
  license: CC BY SA
  page-footer:
    center:
      - text: Copyright 2025, Gerda Wyssen, Enea Weber, Daniel Fitze, and Andrew Ellis
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/kogpsy/neuroscicomplabFS25

  # Book content:
  chapters:
  - index.qmd

  - part: Neurowissenschaftliches Forschen
    chapters:
    - forschungsprozess.qmd # forschungsprozess
    - voraussetzungen.qmd

  - part: Experimentieren & Programmieren
    chapters:
    - experiments.qmd
    - psychopy_experiments.qmd
    - stroop_experiment.qmd
    - random_dot_experiment.qmd
    - intro_python.qmd
    - loops.qmd
    - uebung_1.qmd

  - part: Data wrangling
    chapters:
    - datawrangling.qmd
    - datawrangling_automatisiert.qmd
    - uebung_2.qmd

  - part: Datenvisualisieren
    chapters:
    - data_visualization_1.qmd
    - data_visualization_2.qmd
    - uebung_3.qmd
    - plots_group1.qmd
    - plots_group2.qmd

  - part: Datenanalyse
    chapters:
    - intro_analysis.qmd
    - parameterestimates.qmd
    - hypothesistests.qmd
    - uebung_4.qmd

  - part: Open Science
    chapters:
    - opensci.qmd
    - goodpractices_data.qmd
    - rmarkdown.qmd

  - part: EEG
    chapters:
    - intro_eeg.qmd

  - part: Datenmodellierung
    chapters:
    - modeling.qmd
    - sdt.qmd
    - ddm.qmd

  - part: Anhang
    chapters:
    - webrconsole.qmd
    - license.qmd

number-depth: 3
format:
  html:
    theme:
      light:
      - flatly
      - styles/light.scss
      dark:
      - darkly
      - styles/dark.scss
    css:
    - /styles/global.css
    - include/webex.css
    link-external-newwindow: true
    page-layout: full
    code-background: true
    code-copy: true
    code-overflow: wrap
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt

filters:
  - webr

execute:
  #cache: false
  freeze: true # re-render only when source changes
# #  execute-dir: project

bibliography: bibliography.bib
