project:
  type: book
  output-dir: docs

book:
  title: Neurowissenschaft Computerlab
  subtitle: Frühlingssemester 2025, Universität Bern
 # author: Gerda Wyssen & Enea Weber
 # date: Februar 15, 2025
  edition: 1
  reader-mode: false
  cover-image: imgs/logo.png
  favicon: imgs/logo.png
  site-url: https://kogpsy.github.io/neuroscicomplabFS25/
  page-navigation: true
  search: true
  license: CC BY SA
  page-footer:
    center:
      - text: Copyright 2025, Gerda Wyssen & Enea Weber
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/kogpsy/neuroscicomplabFS25

  # Book content:
  chapters:
  - index.qmd

  - part: Neurowissenschaftliches Forschen
    chapters:
    - forschungsprozess.qmd # forschungsprozess
    - voraussetzungen.qmd

  - part: Experimentieren
    chapters:
    - experiments.qmd
    - psychopy_experiments.qmd
    - stroop_experiment.qmd
    - random_dot_experiment.qmd
    - loops.qmd
    - uebung_1.qmd

  - part: Data wrangling
    chapters:
    - datawrangling.qmd
    - datawrangling_automatisiert.qmd
    - uebung_2.qmd

  - part: Datenvisualisieren
    chapters:
    - data_visualization_1.qmd
    - data_visualization_2.qmd
    - uebung_3.qmd

  - part: Datenanalyse
    #chapters:
    #- uebung_4.qmd

  - part: Datenmodellierung
    #chapters:
    #-

  - part: Anhang
    chapters:
    - webrconsole.qmd
    - license.qmd


number-depth: 3
format:
  html:
    theme:
      light:
      - flatly
      - styles/light.scss
      dark:
      - darkly
      - styles/dark.scss
    css:
    - /styles/global.css
    - include/webex.css
    link-external-newwindow: true
    page-layout: full
    code-background: true
    code-copy: true
    code-overflow: wrap
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt

filters:
  - webr

execute:
  cache: true
  freeze: false # re-render only when source changes
  execute-dir: project

bibliography: bibliography.bib
